export const CLIENTS_GET_START = 'CLIENTS_GET_START';
export const CLIENTS_GET_SUCCESS = 'CLIENTS_GET_SUCCESS';
export const CLIENTS_GET_FAILURE = 'CLIENTS_GET_FAILURE';

export const CLIENT_ADD_START = 'CLIENT_ADD_START';
export const CLIENT_ADD_SUCCESS = 'CLIENT_ADD_SUCCESS';
export const CLIENT_ADD_FAILURE = 'CLIENT_ADD_FAILURE';

export const CLIENT_DELETE_START = 'CLIENT_DELETE_START';
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS';
export const CLIENT_DELETE_FAILURE = 'CLIENT_DELETE_FAILURE';